### ISSUE TITLE
Некорректная работа с сетью

### ISSUE THREAD

**Issue by bogdan1042005** [KirillMonster/GyverLamp2#1]
У вас в коде используется для отправки пакетов `self.__sock.sendto(message.encode(), ('255.255.255.255', self.port))`, но он не работал в моей сети, но если вручную прописать адрес широковещательной рассылки `self.__sock.sendto(message.encode(), ('192.168.1.255', self.port))` то все начинает работать.

**Comment by KirillMonster** [comment]
Спасибо за обратную связь, я пока не занимаюсь этим проектом, но сделаю выбор адреса, планирую его полностью переписать и исправить эту ошибку, да и наверное уберу эту синхронизацию
